### ISSUE TITLE
A question about kernel version which udp.c file is based on

### ISSUE THREAD

**Issue by tiger-yu99** [danluke2/mpudp_vpn_thesis#1]
Hi,
  Excuse me, could you show me the kernel version which your udp.c file is based on.
  I also want to implement mpudp between 2 specific devices, so your implementation is very valuable for me.
  Thanks.

**Comment by danluke2** [comment]
I updated the repo to include my thesis for some extra information.  The kernel version I was using was MPTCP v0.90.  I chose to use the MPTCP kernel so that it could become a full multi path kernel.  I was also using this version since it was the most up to date when I started my thesis work.  The newer versions should work as well.

**Comment by tiger-yu99** [comment]
thanks.
