### ISSUE TITLE
OpenVPN UDP traffic only going through one interface

### ISSUE THREAD

**Issue by BlueWaterCrystal** [danluke2/mpudp_vpn_thesis#4]
So I installed MPTCP with the MPUDP patch and generated the KO files and put them with UDP.c file

But only see data going through one interface on the client on wireshark

set up:
Server: OpenVPN UDP with one interface
Client:  OpenVPN UDP with two interfaces

connected via public IP

I'm guessing I've set something up wrong?

If I read Thesis correctly MPUDP only randomly splits packets between two known address's?

**Comment by danluke2** [comment]
Rite now it is a random since I didn't have the time to work a more complex solution.  You can adjust the randomness in the KO file.

Do you get any errors when you load the KO modules?

Random: in KO send file, adjust the if (t<=16383) to whatever cutoff you want.  This one is a 25% split to new IP source.

KO UDP interface: Make sure you adjust the usin->sin_addr.s_addr to the correct IP addresses for your setup.  The ones in the file assume the setup for the thesis work.  You need to make sure the Send and Receive files also do the IP mapping to the correct addresses.

I assume you also have the MPUDP kernel installed on the client and server, otherwise it won't work.

**Comment by BlueWaterCrystal** [comment]
I've change the interfaces address's to 

Client:
Primary Link: 10.8.1.1
Secondary Link: 10.8.2.2

Server:
Primary Link: 10.8.1.11
Secondary Link: 10.8.2.22

OpenVPN server: 10.8.1.11

assuming it will be the same IP in the KO.



How do I load KO modules?

and when KO module is running it will  allow this code to run?
`		if (mpudp_send_function && (*mpudp_send_function)(usin)){
			daddr = usin->sin_addr.s_addr;
		}`

**Comment by danluke2** [comment]
Loading kernel modules can be found online in various tutorials (e.g., https://opensource.com/article/18/5/how-load-or-unload-linux-kernel-module)

You need to update the KO files for the IP addresses you are using.  You should be able to use the htons(), htonl(), ntohs(), and ntohl() commands to do the conversions.

When the KO module is loaded, the send and receive functions are now defined, so the if checks will pass and run the code
